apiVersion: v1
kind: ReplicationController
metadata:
  name: processor-instance
spec:
  replicas: 2
  selector:
    app: processor-instance
  template:
    metadata:
      name: processor-instance
      labels:
        app: processor-instance
    spec:
      containers:
      - name: processor-instance
        image: dylanmei/zeppelin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80